language: rust
script:
  - cargo build --verbose --release
  - cargo test --verbose
rust:
  - stable
  - beta
  - nightly
os:
  - windows
  - linux
  - osx
before_deploy:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]
    then
      mv target/release/backup-cli.exe backup-cli_windows-x64.exe
      DEPLOY_FILE="backup-cli_windows-x64.exe"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      mv target/release/backup-cli backup-cli_linux-x64
      DEPLOY_FILE="backup-cli_windows-x64.exe"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      mv target/release/backup-cli backup-cli_osx-x64
      DEPLOY_FILE="backup-cli_osx-x64"
    fi
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
deploy:
  provider: releases
  api_key:
    secure: EFHIwYKn2s62LThAQOxJjmPFG30PNrGg4/pUuyu90SDpBETIQaLRyzezl7kcFvqiCQyUsuIphxRTf1RIgI7DzdHqiGp88Z+UfWQYHCf8zpEkNU8EGTAiEy7rF5x52viveo+55v89ajAYWOIwVxM7xauB0UQk1BUT/9VdaQY44lo19pH52U11u5aFQGLuHaSAtW8Qu+17M4ZgR7mZVqniXntt5/WNiIbJbi+czugzvihyPC++iIvlXPWpr/UhD86FMmG/zcsQgpSJY2yXILl8yQnlGpkce9TSJlE3jO1yzs3Kt2xiaBCDrT+oX2NiRf3KfLh0e7A3aQIBLIwyhyL9fUZSLgpPYQi+PIuQfOxxR/FQ08SGUbG5zjHrVGLryeuebSQ0RWsWJkfxVvDvPQAkHhCYifJULIcDpcyfBYrQZ9btwb8Czy0An1R3rkNOaS+tFPXEkgGqpwshGxqiyZDeDMv3eHA7RxG8R7jscc37lYS5q74IK6KBh2wO6GuilB0CXt3MnIoiv7BodByXPBcG71DsUg6P3PttQVpMPbNM52Y0cN4XjFX+wOiezjX9JMCPj3vG/sN8IchYnqLlnsPu07fmQipQgm0QkQw4ZBIiW2nTuNAOd/ZBdLl+MAfK4tUkgDU7W8uatKwXv7yO5pX6jspwDLb9hHqLCw3jvQAWY2o=
  file: $DEPLOY_FILE
  skip_cleanup: true
  # Comment if we don't want to overview the
  # release before actually making it public.
  draft: true
  on:
    repo: Lieturd/backup-cli
    branch: master
    condition: $TRAVIS_RUST_VERSION = "stable"
    tags: true